### ISSUE TITLE
Implement further transmission options of email contents

### ISSUE THREAD

**Issue by ffried** [sersoft-gmbh/swift-smtp#7]
Certain servers have problems if the lines get too long. #6 describes a case where the server simply truncates the lines and thus the email appears blank when delivered.

This could be resolved by adding further transmission options. The following options come to mind:
- base64-only option with the ability to specify the maximum line length
- a line-limit option which manually inserts CRLF's after a given line length

**Comment by lmcd** [comment]
I think the proper resolution is as I described previously - base64 encode everything, including plaintext with a maximum line length of 76. I think this is the only way to guarantee full compatibility
